### PR TITLE
Script to run object detection in a video stream

### PR DESCRIPTION
**Pull request by jantielens**
Added a new script (based on the webcam script) which will run the object detection on a video stream (instead of the local webcam). This video stream can be the URL of a remote webcam, a security camera ... The script has been tested with MJPEG and RTSP streams, but in theory all codecs supported by CV2 should be usable.

### CODE REVIEW

**Comment by EdjeElectronics** [comment]
Hey @jantielens , thanks again for submitting this PR. It looks great, but I want to test it out on my Pi before I merge it. I'll do that some time this week!

**Comment by jantielens** [comment]
Hi, did you get a chance to test this? If not, no worries. 😄 
If so and you don't feel this code belongs in your repo, feel free to let me know. (then I can host/mantain the addition on another repo)

Thanks,
J

**Comment by EdjeElectronics** [comment]
Hey Jan, I haven't got a chance to test it yet! Sorry, life has been keeping me very busy the past few months. I do appreciate your contribution and want to keep it on this repo :smile: ! I will put it on my to-do list to get it tested next week.

**Comment by jantielens** [comment]
No worries! Thanks for letting me know, so I'm not going to put any effort in creating a new repo. 😃 Have a great weekend.

**Comment by EdjeElectronics** [comment]
I'm still planning to test this! It will be tomorrow or Wednesday :)

**Pull request merged**
